name: Push images to Dockerhub and deploy on Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build_docker_images:
    name: build docker images
    runs-on: ubuntu-latest
    steps:
    # clones repository for working with it 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build Server image
        run: docker build -t cpg3/salzbike .

      - name: Tag the Image
        run: docker tag cpg3/salzbike cpg3/salzbike:latest

      - name: Push to dockerhub
        run: docker push cpg3/salzbike
      - name: Fetch all tags
        run: git fetch --tags

      - name: Increment version tag
        id: versioning
        run: |
          # Get the latest version tag
          LATEST_VERSION=$(git describe --tags --match "salzbike-version-*" | sort -V | tail -n 1)
          # Extract the number from the version tag
          NUMBER=$(echo $LATEST_VERSION | grep -o -E '[0-9]+')
          # Increment the version number
          NEW_NUMBER=$((NUMBER + 1))
          # Set the new version tag as output
          echo "::set-output name=version::salzbike-version-$NEW_NUMBER"
          echo "New version: salzbike-version-$NEW_NUMBER"
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
         aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
         application_name: salzbike
         environment_name: Salzbike-env
         region: eu-central-1
         version_label: ${{ steps.versioning.outputs.version }}

      - name: Push new tag to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.versioning.outputs.version }}
          git push origin ${{ steps.versioning.outputs.version }}

